### ISSUE TITLE
[feature] [v0.2] [comet] Group spiketrains for testing

### ISSUE THREAD

**Issue by morales-gregorio** [INM-6/NetworkUnit#18]
Hey! 

@rgutzen and I have been thinking a lot about how to group spiketrains into some tests.

In our use case, we have a long list of spiketrains which were recorded in different days and sessions. These is fine for single unit kind of tests (FR, CV, LV, timescale...), but not so for pairwise tests. We want to apply the following pairwise tests:
a) Correlation coefficients (and actually take the mean/std to collapse it into a single unit metric)
b) Spike triggered population response (stPR, single unit metric versus the rest of the population!) (currently [being implemented into elephant](https://github.com/NeuralEnsemble/elephant/pull/324))

Grouping the spiketrains by date or area is relatively easy, because this information is included in the annotations. However, the main problem is that we do not know what is the best way to integrate it into NetworkUnit/SciUnit. We have considered the following options, but none of them has convinced us:
1. Create a `grouped_test_xxx` class that would inherit the corresponding pairwise test and overwrite the `generate_predictions`. This is quite blunt, since it requires rewriting all the tests of interest (so far only two, but maybe some other tests join the pairwise club) and is therefore not very generalizable.

2. Create a decorator to do the grouping before `generate_predictions`. This option has some potential. The decorator would add some boilerplate before and after the function, first to group the spiketrains then run the predictions in a loop and finally merge them back. The advantage is that it would not require editing the original tests. One big problem however is that the way that NetworkUnit is structured it produces the spiketrains inside of `generate_predictions`, which would be required for the grouping. So that if a decorator is to be used it would require separating this function, which is definitely not ideal! Following from this line some sort of hacky solution could exists like making the `generate_predicitions` call some other function and decorate that one.

3. Run the correlation for all spiketrain pairs and select only the relevant values. Unnecessary waste of computation, would not work for stPR anyway.

4. Add an option into the relevant tests to do this. Same as writing a custom inheriting test, not very general, but maybe it is cleaner. 

5. Split the model instance into grouped child instances. This has some issues like how the model instance links to the memory/disk. However, if completely new instances are created for which the predictions are generated and then they are merged again. Not certain where this would have to happen (which is actually the point of this whole issue). I would suggest building this as a new test class, however due to the splitting into grouped model instances it would not need tweaking the original test code, which makes it more general. Might have to discuss this one more in detail. 

In all, I would say that option 1 is the best so far even though it is not generalizable at all. Option 5 also has a lot of potential in my opinion, and if executed cleanly (such that the grouped model child instances are not messing with the parent) it can actually be very generalizable, but many open questions remain.

I believe this issue is quite fundamental to any pairwise metric, and can actually be a very useful feature not only in the context of our project.

@rgerkin please let us know if you have any thoughts on this :)

Cheers,
Aitor

**Comment by rgerkin** [comment]
As it stands now, is a single spike train the `observation` that is uses to instantiate the `Test` for most tests?  And does the `observation` contain a pair of spike trains for things like a correlation test?   If so, I would extend the `observation` to be a group of many spike trains, but with annotations.  You can create an `observation_schema` which `validate_observation` will use to make sure that what you have provided is reasonable.  For example, it might allow a list of spike trains, or also allow a dictionary where keys are group names and values are list of spike trains for that group.  

Then I would have one general method to operate within a group, to produce something like an NxN correlation matrix (or whatever).  Another method could collapse this to a single mean/std pair, and another method could aggregate across mean/std pairs.

**Comment by rgutzen** [comment]
The application we have in mind is specific to a capability `ProducesSpiketrains`, so there is a call to the corresponding `produce_spiketrains()` function in  `generate_prediction()`. Thus, predictions are generally computed based on a list of spiketrains.
A normal test for a pairwise measure (e.g. correlation) would compute the NxN matrix, plus eventual further processing. Adding grouping according to some attribute of the spiketrains would require to already change the matrix creation somehow to generate a list of matrices [N1xN1; N2xN2; ...].
As I'm realizing now, a general solution might be to perform the grouping already in the function `produce_spiketrains()` which is defined in the model, and adapt the `generate_prediction()` function of the eligible tests to also accept lists of lists of spiketrains.
The remaining issue would just be how to elegantly invoke `compute_score()` for each group's prediction and observation (or 2nd predictions, since we are working mostly with M2MTests).

**Comment by rgerkin** [comment]
This sounds reasonable, but be sure to make the structure of whatever `produce_spiketrains()` returns consistent across test types that might require it.

**Comment by rgutzen** [comment]
The most sensible solution we could come up with is implemented in commit fc7817b5c855412fe3d9ac315f70faade850d062 which introduces the capability ProducesListsOfSpikeTrains which is used in the average_correlation_test.

**Comment by rgerkin** [comment]
Alternatively, you don't need to generate a entirely new Capability class just for a related kind of output; you can just add that method to the original one.  By default it could be:

```
class ProducesSpikeTrains(sciunit.Capability):
    def produce_spiketrains(self):
        raise NotImplementedError("")
    
    def produce_listsofspiketrains(self):
        raise NotImplementedError("")
```

or if you want a default implementation:

```
class ProducesSpikeTrains(sciunit.Capability):
    def produce_spiketrains(self):
        raise NotImplementedError("")
    
    def produce_listsofspiketrains(self):
        return list(self.produce_spiketrains())
```

which the model would then override.

The question of "how related" two capability methods have to be to belong in the same capability class is an open one, and I'm not saying your choice was wrong, but this is something to think about when you have this kind of situation.

**Comment by rgutzen** [comment]
@rgerkin, thanks, that's a good point. These capabilities are definitely related enough since the list of spiketrain-lists can always default to a list with a single element. I will update the scripts.

**Comment by morales-gregorio** [comment]
Awesome! :)
