### ISSUE TITLE
Allow SciUnit >= 0.2.7

### ISSUE THREAD

**Issue by heplesser** [INM-6/networkunit#31]
@rgutzen Currently, Networkunit requires exactly SciUnit 0.2.7. Now that SciUnit 0.2.8 is out (at least on Github), I'd much appreciate if Networkunit would work with 0.2.8 as well, since that versions is compatible with Python 3.11—at least it imports under 3.11. I have tested the two `*_test.ipynb` notebooks in the example directory and they work.

**Comment by rgutzen** [comment]
Thanks for the note. I updated the requirements accordingly. Unfortunately, package requirements can only contain versions on Pypi and not from Github. Therefore, Networkunit will still depend on Sciunit 0.2.7 until a new release on Pypi exists. However, you can always install a newer version from Github manually.

**Comment by heplesser** [comment]
@rgutzen Thanks! SciUnit 0.2.8 is available on PyPi now (https://pypi.org/project/sciunit/). Could you create a NetworkUnit 0.2.2 release with the latest changes and make it available on PyPi?

**Comment by rgutzen** [comment]
The updated Networkunit 0.2.2 is now on Pypi.
