### ISSUE TITLE
Sciunit Feature Requests or Changes?

### ISSUE THREAD

**Issue by rgerkin** [INM-6/NetworkUnit#5]
@rgutzen I'm the lead developer for sciunit and I wanted to ask if you had any questions, feature requests, bug reports, or anything else I can help out with to make your sciunit-based project work as well as possible?

**Comment by rgutzen** [comment]
Thank you for reaching out. Your software was immensely useful in the development of this project. I added two issues in the sciunit repository for obstacles I encountered and bypassed which may be also relevant for other projects and could be dealt with within sciunit.
